import type { NextPage } from 'next'
import Head from 'next/head'
import {gql, useQuery} from "@apollo/client";

const ViewerQuery = gql`
  query ViewerQuery {
    viewer {
      id
      name
      status
    }
  }
`


const Home: NextPage = () => {
  const {
    data: { viewer } = {},
  } = useQuery(ViewerQuery)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome {viewer?.name} to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  )
}

export default Home
